import Head from 'next/head'
import { Navigation } from './Navigation'


export const Container = (props) => {
    return (
        <>
            <Head>
                <title>LearnNext</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation/>
            <main>
                {props.children}
            </main>
            <footer className='flex justify-center p-4 bg-blue-50'>
                <div>
                    <p className='capitalize font-bold'>powered by <a className='text-blue-900 hover:underline' href="https:instagram.com/jsalamanc" target='_blank'>jsalamanc</a></p>
                </div>
            </footer>
        </>
    )
}
